---
swagger: "2.0"
info:
  description: "This is hello world swagger API application."
  version: "1.0.0"
  title: "Smart recycling bins"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "none@test.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "hello world"
  description: "get static answer to test API"
schemes:
- "http"
paths:
  /helloWorld:
    get:
      tags:
      - "hello world"
      summary: "Get hello world response"
      description: "Get hello world response"
      operationId: "get_hello_world"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
            example: "hello"
        400:
          description: "Invalid query"
      x-swagger-router-controller: "swagger_server.controllers.hello_world_controller"
  /data:
    post:
      tags:
      - "data"
      summary: "Add data sample"
      description: "Add data sample"
      operationId: "add_data"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Add data sample"
        required: false
        schema:
          $ref: "#/definitions/Data"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Data"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.data_controller"
definitions:
  Data:
    type: "object"
    required:
    - "data"
    - "id"
    - "mac"
    - "time"
    properties:
      id:
        type: "integer"
        format: "int64"
      mac:
        type: "string"
        format: "mac"
      data:
        type: "number"
        format: "double"
      time:
        type: "string"
        format: "date-time"
    example:
      id: 0
      mac: "00:AA:BB:CC:DD:DD"
      data: 6.6500000000000003552713678800500929355621337890625
      time: "2000-01-23T04:56:07.000+00:00"
    xml:
      name: "Data"
